# Welcome to Jekyll!
#

# Site settings
title: Mark Lummus
subtitle: Atlanta Fractional CTO to non-technical founders and emerging businesses
xsite_name: Mark Lummus
owner: Mark Lummus # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: mark@marklummus.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.marklummus.com" # the base hostname & protocol for your site
github_username:  jabbermarky
timezone: America/New_York
include: ["_pages"]
author: marklummus
twitter:
  username: marklummus
social:
  twitter: https://twitter.com/marklummus
  #github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/marklummus
  #facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+marklummus
  email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  angellist: https://angel.co/mark-marklummus-com
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
collections:
  portfolio:
    output: true
    title: Portfolio
    permalink: /portfolio/:path/
